import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import {Outer} from 'next/font/google' 
import { ClerkProvider , SignedIn, SignedOut, SignInButton, UserButton} from '@clerk/nextjs' 
import {Toaster} from 'sonner'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "QuikSend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return ( 
    <ClerkProvider>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
         
        

        {children} 
        <Toaster position="top-center"/>
      </body>
    </html>
    </ClerkProvider>
  );
}
